### ISSUE TITLE
Cromlech Container Compile bug

### ISSUE THREAD

**Issue by clozinski** [Cromlech/cromlech.container#1]
class Contained(object):
  File "/home/lozinski/code/cromlech/ZODBDemo/eggs/cromlech.container-0.1-py2.7.egg/c\
romlech/container/contained.py", line 21, in Contained
    implements(IContained)
  File "/home/lozinski/code/cromlech/ZODBDemo/eggs/zope.interface-4.4.3-py2.7-linux-x\
86_64.egg/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator \
instead.

**Comment by clozinski** [comment]
I am running in Python 3.4.2 on linux.

**Comment by trollfot** [comment]
It is fixed. Please, read the comment on the latest commit, to see the status.
